### ISSUE TITLE
ExchangeHub

### ISSUE THREAD

**Issue by identithree** [bowlingballindustries/spookvooper-api#16]
# ExchangeHub Issue
We need to get ExchangeHub done

## To-do List
 - [x] Copy boilerplate code from [TransactionHub](https://github.com/vexico/spookvooper-api/blob/development/src/modules/TransactionHub.ts)
 - [x] Add `StockOffer` listener
 - [x] Add `StockOfferCancel` listener
 - [x] Add `StockTrade` listener
 - [x] Add `RecieveMessage` listener
 - [x] Add `RecieveMessageHistory` listener
 - [x] Configure system to send commands to ExchangeHub
 - [x] Add required types and interfaces

## Metadata (as of writing)
**Labels**: Enhancement, Doing
**Assignee**: @brndnln 
**Project**: [Development Board](https://github.com/vexico/spookvooper-api/projects/1)
**Milestone**: [TS Rewrite](https://github.com/vexico/spookvooper-api/milestone/1)
**Linked Pull Request**: #13
